-- =========================================================================
-- Customer Data Analytics Project (SQL Server / T-SQL)
-- Cleaned, formatted, and documented for learning purposes.
-- =========================================================================

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM customer_data 
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount 
FROM customer_data
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer_data 
GROUP BY item_purchased
ORDER BY average_product_rating DESC;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer_data 
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, average_purchase_amount DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased AS products,
    ROUND(CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*) * 100, 2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_data
)
SELECT 
    customer_segment, 
    COUNT(*) AS Number_of_Customer
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
-- Note: Semicolon added right before WITH to prevent MS SQL Msg 319 error.
;WITH ProductSales AS (
    SELECT 
        category,
        item_purchased AS product_name,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS ranking
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT 
    category,
    product_name,
    total_purchases
FROM ProductSales
WHERE ranking <= 3
ORDER BY category, ranking;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;